### ISSUE TITLE
About installation

### ISSUE THREAD

**Issue by smallfishcui** [IDEELResearch/vcfdo#4]
Hi,

I just posted and closed an issue, but now I have a new one. So I am able to install the packages, and am able to find the location. When I type vcfdo --help, the error message is like this:
Traceback (most recent call last):
  File "/home/cuiwang/.local/bin/vcfdo", line 16, in <module>
    import pybedtools as pbt
  File "/home/cuiwang/.local/lib/python3.6/site-packages/pybedtools/__init__.py", line 10, in <module>
    from .cbedtools import (Interval, IntervalFile, overlap, Attributes,
ImportError: /home/cuiwang/.local/lib/python3.6/site-packages/pybedtools/cbedtools.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

Do this mean a failure of installation?

thanks,
Cui

**Comment by andrewparkermorgan** [comment]
Yes, this means that `pybedtools` (on which `vcfdo` depends) is not installed properly. Note that `pybedtools` is a Python wrapper around `bedtools` -- check that you have both in your `conda` environment or in the global environment.

**Comment by smallfishcui** [comment]
Thank you Andrew for your quick response! I got it running after giving an executable path, but I get other problems. I will close this one and put it in another issue.
