### ISSUE TITLE
Error on Python 3.7

### ISSUE THREAD

**Issue by alanorth** [IDEELResearch/vcfdo#7]
Trying to run vcfdo on Python 3.7.10 and getting the following error:

```console
$ vcfdo 
Traceback (most recent call last):
  File "/export/apps/vcfdo/git-fa42fe09/bin/vcfdo", line 2162, in <module>
    logger.info("Task: {}".format(args.command))
AttributeError: 'Namespace' object has no attribute 'command'
```

What version is this expected to run on? The dependencies are not pinned and recent scipy etc need Python 3.7+.

**Comment by andrewparkermorgan** [comment]
I developed it under Python 3.5.2 but that's not the issue. I did not code the command-line parsers properly for the case when no subcommand is given. That should be fixed now.

**Comment by alanorth** [comment]
Ah that's great. An easy fix! It's working for me.  Thank you.

So now it seems that the minimum version is Python 3.7 because that's the minimum required by current scipy and or numpy. Python 3.5 is end of life, but you could still support Python 3.6+ if you wanted by pinning some older scipy/numpy version (for example with poetry or pipenv).
